# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://somnathrakshit.github.io/geograpy_new/"

git_url = "https://github.com/somnathrakshit/geograpy_new/tree/master/"

def custom_doc_links(name): return None
