# AUTOGENERATED! DO NOT EDIT! File to edit: 001_labels.ipynb (unless otherwise specified).

__all__ = ['Labels']

# Cell
class Labels(object):
    '''
    NLTK labels
    '''
    default=['GPE','GSP','PERSON','ORGANIZATION']
    geo=['GPE','GSP']